services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: postgres
    ports:
      - 5432:5432
    env_file:
      - ./../.env
    volumes:
      - postgres:/var/lib/postgresql/
      - ./data:/tmp
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  postgres: